frontend/controllers/BlogController.php
<?
/**
 * Created by PhpStorm.
 * User: sebulbawork
 * Date: 30.08.17
 * Time: 10:29
 */
namespace frontend\controllers;

use common\models\Article;
use common\models\Tag;
use yii\web\Controller;

class BlogController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index', [
            'articleDataProvider' => (new Article)->dataProvider,
            'tagDataProvider' => (new Tag)->dataProvider,
        ]);
    }

    public function actionView($id)
    {
        $blog_model = (new Article)->find()->where($id)->one();

        return $this->render('view', ['model' => $blog_model]);
    }
}

frontend/views/blog/index.php
<?
/**
 * Created by PhpStorm.
 * User: sebulbawork
 * Date: 29.08.17
 * Time: 15:23
 */
?>

<?

/* @var $this yii\web\View */

$this->title = 'Блог';
?>

<?
use yii\widgets\Pjax;
?>

<!-- Blog -->
<section class="well-sm-2">
    <div class="container" data-lightbox="gallery">
        <h2 class="line-3">Блог</h2>
        <p class="text-default-2 inset-1 offset-3 letter-spacing-1">Fresh real estate news</p>

        <? Pjax::begin() ?>

        <?= $this->render('/tag/list', ['dataProvider' => $tagDataProvider]) ?>

        <?= $this->render('/blog/list', ['dataProvider' => $articleDataProvider]) ?>

        <? Pjax::end() ?>

    </div>
</section>
<!-- END Blog -->

frontend/views/blog/item.php
<?
/**
 * Created by PhpStorm.
 * User: sebulbawork
 * Date: 29.08.17
 * Time: 15:27
 */
?>

<?
use yii\helpers\Url;
?>

<li>
    <img width="1170" height="447" alt="" src="<?= $model->image ?>">
    <h3>
        <a href="#">
            <?= $model->caption ?>
        </a>
    </h3>
    <div>
        <time datetime="<?= Yii::$app->formatter->asDate($model->date, 'yyyy-MM') ?>">
            <span class="fa fa-calendar"></span>
            <? Yii::$app->formatter->locale = 'en-US' ?>
            <a href="#">
                <?= Yii::$app->formatter->asDate($model->date) ?>
            </a>
        </time>
        <p><span class="fa fa-user"></span><a href="#">Admin</a></p>
        <p><span class="fa fa-comments"></span><a href="#">0 Comments</a></p>
    </div>
    <p>
        <?= $model->short_description ?>
    </p>
    <a class="btn btn-xs btn-primary" href="<?= Url::toRoute(['blog/view', 'id' => $model->id]) ?>">
        Читать далее...
        <span></span>
    </a>
</li>

frontend/views/blog/list.php
<?
/**
 * Created by PhpStorm.
 * User: sebulbawork
 * Date: 30.08.17
 * Time: 11:03
 */
use yii\widgets\ListView;
?>

<?=
ListView::widget([
    'dataProvider' => $dataProvider,
    'layout' => '{pager}{items}{pager}',
    'options' => [
        'tag' => 'ul',
        'class' => 'list-2'
    ],
    'itemOptions' => [
        'tag' => 'li'
    ],
    'itemView' => 'item',
    'showOnEmpty' => false,
    'emptyText' => 'Статей, включающих в себя такие теги, не обнаружено.'
])
?>

frontend/views/blog/view.php
<?
/**
 * Created by PhpStorm.
 * User: sebulbawork
 * Date: 29.08.17
 * Time: 15:34
 */
?>

<section class="well-sm-2">
    <div class="container">
        <?=
        $model->content
        ?>
    </div>
</section>