common/models/Tag.php
<?php

namespace common\models;

use Yii;
use yii\data\ActiveDataProvider;

/**
 * This is the model class for table "tag".
 *
 * @property integer $id
 * @property string $name
 *
 * @property ArticleTag[] $articleTags
 */
class Tag extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tag';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticleTags()
    {
        return $this->hasMany(ArticleTag::className(), ['tag_id' => 'id']);
    }

    public function getDataProvider()
    {
        return new ActiveDataProvider([ 'query' => $this->find() ]);
    }

    public function getHref($route = null)
    {
        $get = Yii::$app->request->get('tags') ?: [];

        $id = $this->id;

        $tags = in_array($id, $get)
            ? (array_filter($get, function ($i) use ($id) { return $i != $id; }))
            : array_merge($get, [$id]);

        return [
            implode('/', $route),
            'tags' => $tags
        ];
    }

    public function getClass($class = null)
    {
        return !in_array($this->id, (Yii::$app->request->get('tags') ?: [])) ?: $class;
    }
}

frontend/controllers/BlogController.php
<?
/**
 * Created by PhpStorm.
 * User: sebulbawork
 * Date: 30.08.17
 * Time: 10:29
 */
namespace frontend\controllers;

use common\models\Article;
use common\models\Tag;
use yii\web\Controller;

class BlogController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index', [
            'articleDataProvider' => (new Article)->dataProvider,
            'tagDataProvider' => (new Tag)->dataProvider,
        ]);
    }

    public function actionView($id)
    {
        $blog_model = (new Article)->find()->where($id)->one();

        return $this->render('view', ['model' => $blog_model]);
    }
}

frontend/views/tag/item.php
<?
/**
 * Created by PhpStorm.
 * User: sebulbawork
 * Date: 30.08.17
 * Time: 10:44
 */
?>

<?
use yii\helpers\Url;
use yii\helpers\Html;
?>
<div class="item <?= $model->getClass('selected') ?>">
    <?=
    Html::a(
        mb_strtolower($model->name),
        Url::toRoute($model->getHref(['blog', 'index'])),
        ['class' => ['link']]
    );
    ?>
</div>

frontend/views/tag/list.php
<?
/**
 * Created by PhpStorm.
 * User: sebulbawork
 * Date: 30.08.17
 * Time: 10:59
 */
use yii\widgets\ListView;
use yii\helpers\Html;
use yii\helpers\Url;
use frontend\assets\CloudAsset;

CloudAsset::register($this);
?>

<?
$clear_link = Html::a(
    'Очистить фильтр',
    Url::toRoute(['blog/index']),
    [ 'class' => 'clear-all' ]
);
?>

<?=
ListView::widget([
    'dataProvider' => $dataProvider,
    'layout' => "{items}$clear_link",
    'options' => ['class' => 'tag-cloud'],
    'itemOptions' => ['tag' => null],
    'itemView' => '/tag/item',
])
?>